# Generated by Django 5.2.7 on 2025-11-04 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='বইয়ের নাম')),
                ('author', models.CharField(max_length=100, verbose_name='লেখক')),
                ('description', models.TextField(verbose_name='বিবরণ')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='প্রচ্ছদ')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdf/', verbose_name='PDF ফাইল')),
                ('publication_date', models.DateField(verbose_name='প্রকাশনার তারিখ')),
                ('is_available', models.BooleanField(default=True, verbose_name='উপলব্ধ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
            ],
            options={
                'verbose_name': 'বই',
                'verbose_name_plural': 'বইসমূহ',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='বিভাগের নাম')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL স্লাগ')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
            ],
            options={
                'verbose_name': 'বিভাগ',
                'verbose_name_plural': 'বিভাগসমূহ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('email', models.EmailField(max_length=254, verbose_name='ইমেইল')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='ফোন')),
                ('subject', models.CharField(max_length=200, verbose_name='বিষয়')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
                ('is_read', models.BooleanField(default=False, verbose_name='পড়া হয়েছে')),
            ],
            options={
                'verbose_name': 'যোগাযোগ',
                'verbose_name_plural': 'যোগাযোগসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='অনুষ্ঠানের নাম')),
                ('description', models.TextField(verbose_name='বিবরণ')),
                ('date_time', models.DateTimeField(verbose_name='তারিখ ও সময়')),
                ('location', models.CharField(max_length=200, verbose_name='স্থান')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='প্রধান ছবি')),
                ('is_featured', models.BooleanField(default=False, verbose_name='বৈশিষ্ট্যযুক্ত')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
            ],
            options={
                'verbose_name': 'অনুষ্ঠান',
                'verbose_name_plural': 'অনুষ্ঠানসমূহ',
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('gallery_type', models.CharField(choices=[('photo', 'ছবি'), ('video', 'ভিডিও')], default='photo', max_length=10, verbose_name='গ্যালারির ধরণ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='ছবি')),
                ('video_url', models.URLField(blank=True, verbose_name='ভিডিও লিংক')),
                ('is_featured', models.BooleanField(default=False, verbose_name='বৈশিষ্ট্যযুক্ত')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
            ],
            options={
                'verbose_name': 'গ্যালারি',
                'verbose_name_plural': 'গ্যালারিসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='দুর্গা মন্দির', max_length=200, verbose_name='সাইটের নাম')),
                ('site_tagline', models.CharField(blank=True, max_length=200, verbose_name='সাইটের স্লোগান')),
                ('site_description', models.TextField(blank=True, verbose_name='সাইটের বিবরণ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='লোগো')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='ফ্যাভিকন')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='যোগাযোগের ইমেইল')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='যোগাযোগের ফোন')),
                ('address', models.TextField(blank=True, verbose_name='ঠিকানা')),
                ('facebook_url', models.URLField(blank=True, verbose_name='ফেসবুক পাতা')),
                ('youtube_url', models.URLField(blank=True, verbose_name='ইউটিউব চ্যানেল')),
                ('footer_text', models.TextField(blank=True, verbose_name='ফুটার টেক্সট')),
            ],
            options={
                'verbose_name': 'সাইট সেটিংস',
                'verbose_name_plural': 'সাইট সেটিংস',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL স্লাগ')),
                ('content', models.TextField(verbose_name='বিষয়বস্তু')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='সারসংক্ষেপ')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='প্রধান ছবি')),
                ('is_published', models.BooleanField(default=True, verbose_name='প্রকাশিত')),
                ('is_featured', models.BooleanField(default=False, verbose_name='বৈশিষ্ট্যযুক্ত')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='সর্বশেষ আপডেট')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='লেখক')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='durga.category', verbose_name='বিভাগ')),
            ],
            options={
                'verbose_name': 'প্রবন্ধ',
                'verbose_name_plural': 'প্রবন্ধসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='পাতার শিরোনাম')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL স্লাগ')),
                ('content', models.TextField(verbose_name='বিষয়বস্তু')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='মেটা বিবরণ')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='প্রধান ছবি')),
                ('is_published', models.BooleanField(default=True, verbose_name='প্রকাশিত')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='মেনুতে দেখান')),
                ('menu_order', models.IntegerField(default=0, verbose_name='মেনু ক্রম')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='সর্বশেষ আপডেট')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='লেখক')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durga.page', verbose_name='মূল পাতা')),
            ],
            options={
                'verbose_name': 'পাতা',
                'verbose_name_plural': 'পাতাসমূহ',
                'ordering': ['menu_order', 'title'],
            },
        ),
    ]
