# Generated by Django 5.2.7 on 2025-11-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='উপশিরোনাম')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='স্লাইডার ছবি')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='বাটনের টেক্সট')),
                ('button_link', models.CharField(blank=True, max_length=200, verbose_name='বাটনের লিংক')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
            ],
            options={
                'verbose_name': 'স্লাইডার',
                'verbose_name_plural': 'স্লাইডারসমূহ',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
