# Generated by Django 5.2.7 on 2025-11-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0002_slider'),
    ]

    operations = [
    ]
