# Generated by Django 5.1.5 on 2025-11-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0003_auto_20251104_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='অ্যালবামের নাম')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('cover_image', models.ImageField(upload_to='albums/covers/', verbose_name='কভার ছবি')),
                ('is_featured', models.BooleanField(default=False, verbose_name='বৈশিষ্ট্যযুক্ত')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
            ],
            options={
                'verbose_name': 'গ্যালারি অ্যালবাম',
                'verbose_name_plural': 'গ্যালারি অ্যালবামসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='ছবির নাম')),
                ('image', models.ImageField(upload_to='albums/photos/', verbose_name='ছবি')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='আপলোড তারিখ')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='durga.galleryalbum', verbose_name='অ্যালবাম')),
            ],
            options={
                'verbose_name': 'গ্যালারি ছবি',
                'verbose_name_plural': 'গ্যালারি ছবিসমূহ',
                'ordering': ['created_at'],
            },
        ),
    ]
