# Generated by Django 5.1.5 on 2025-11-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0004_galleryalbum_galleryphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('position', models.CharField(choices=[('president', 'সভাপতি'), ('vice_president', 'সহ-সভাপতি'), ('secretary', 'সাধারণ সম্পাদক'), ('joint_secretary', 'যুগ্ম সম্পাদক'), ('treasurer', 'কোষাধ্যক্ষ'), ('organizer', 'সংগঠক'), ('advisor', 'উপদেষ্টা'), ('member', 'সদস্য')], max_length=20, verbose_name='পদবী')),
                ('image', models.ImageField(upload_to='committee/', verbose_name='ছবি')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='মোবাইল নাম্বার')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ইমেইল')),
                ('address', models.TextField(blank=True, verbose_name='ঠিকানা')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='যোগ করার তারিখ')),
            ],
            options={
                'verbose_name': 'কমিটির সদস্য',
                'verbose_name_plural': 'কমিটির সদস্যবর্গ',
                'ordering': ['order', 'name'],
            },
        ),
    ]
