# Generated by Django 5.1.5 on 2025-11-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0005_committeemember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeemember',
            name='address',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='email',
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='position',
            field=models.CharField(max_length=100, verbose_name='পদবী'),
        ),
    ]
