# Generated by Django 5.1.5 on 2025-11-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0006_remove_committeemember_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurgaSangha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('position', models.CharField(max_length=100, verbose_name='পদবী')),
                ('image', models.ImageField(upload_to='durga_sangha/', verbose_name='ছবি')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='মোবাইল নাম্বার')),
                ('description', models.TextField(blank=True, null=True, verbose_name='বিবরণ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='যোগ করার তারিখ')),
            ],
            options={
                'verbose_name': 'দুর্গা সংঘের সদস্য',
                'verbose_name_plural': 'দুর্গা সংঘের সদস্যবর্গ',
                'ordering': ['order', 'name'],
            },
        ),
    ]
