# Generated by Django 5.1.5 on 2025-11-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0007_durgasangha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryalbum',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='albums/covers/', verbose_name='কভার ছবি'),
        ),
    ]
