# Generated by Django 5.1.5 on 2025-11-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0008_alter_galleryalbum_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
