# Generated by Django 5.1.5 on 2025-11-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0009_remove_article_author_remove_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='ফোন'),
        ),
    ]
