# Generated by Django 5.1.5 on 2025-11-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0010_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='যোগাযোগের ফোন'),
        ),
    ]
