# Generated by Django 5.2.7 on 2025-11-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0011_alter_sitesettings_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_map_url',
            field=models.TextField(blank=True, help_text='গুগল ম্যাপের এম্বেড কোড এখানে পেস্ট করুন', verbose_name='গুগল ম্যাপ এম্বেড URL'),
        ),
    ]
