# Generated by Django 5.2.7 on 2025-11-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0012_sitesettings_google_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurgaPujaCountdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='দুর্গা পূজা', max_length=200, verbose_name='অনুষ্ঠানের নাম')),
                ('target_date', models.DateTimeField(verbose_name='লক্ষ্য তারিখ')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='countdown/', verbose_name='ব্যাকগ্রাউন্ড ছবি')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('message_before', models.CharField(default='মা আসছে', max_length=100, verbose_name='পূর্বের বার্তা')),
                ('message_after', models.CharField(default='দিন পরে', max_length=100, verbose_name='পরের বার্তা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
            ],
            options={
                'verbose_name': 'দুর্গা পূজা কাউন্টডাউন',
                'verbose_name_plural': 'দুর্গা পূজা কাউন্টডাউনসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
