# Generated by Django 5.2.7 on 2025-11-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0013_durgapujacountdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='PujaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='পূজার দিনের নাম')),
                ('date', models.DateField(verbose_name='তারিখ')),
                ('image', models.ImageField(upload_to='puja_days/', verbose_name='ছবি')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রম')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
            ],
            options={
                'verbose_name': 'পূজার দিন',
                'verbose_name_plural': 'পূজার দিনসমূহ',
                'ordering': ['order', 'date'],
            },
        ),
    ]
