# Generated by Django 5.2.7 on 2025-11-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0014_pujaday'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='category',
            field=models.CharField(choices=[('executive', 'কার্যনির্বাহী কমিটি'), ('advisory', 'উপদেষ্টা পরিষদ'), ('special', 'বিশেষ সদস্য')], default='executive', max_length=20, verbose_name='ক্যাটাগরি'),
        ),
    ]
