# Generated by Django 5.2.7 on 2025-11-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0015_committeemember_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='category',
            field=models.CharField(default='কার্যনির্বাহী কমিটি', help_text='যেমন: কার্যনির্বাহী কমিটি, উপদেষ্টা পরিষদ, বিশেষ সদস্য', max_length=100, verbose_name='ক্যাটাগরি'),
        ),
    ]
