# Generated by Django 5.2.7 on 2025-11-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0016_alter_committeemember_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeemember',
            options={'ordering': ['category_order', 'order', 'name'], 'verbose_name': 'কমিটির সদস্য', 'verbose_name_plural': 'কমিটির সদস্যবর্গ'},
        ),
        migrations.AddField(
            model_name='committeemember',
            name='category_order',
            field=models.PositiveIntegerField(default=0, help_text='ছোট সংখ্যা আগে দেখাবে (যেমন: 1, 2, 3...)', verbose_name='ক্যাটাগরির ক্রম'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='একই ক্যাটাগরির মধ্যে সদস্যের ক্রম', verbose_name='সদস্যের ক্রম'),
        ),
    ]
