# Generated by Django 5.2.7 on 2025-11-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0017_alter_committeemember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='durgasangha',
            options={'ordering': ['category_order', 'order', 'name'], 'verbose_name': 'দুর্গা সংঘের সদস্য', 'verbose_name_plural': 'দুর্গা সংঘের সদস্যবর্গ'},
        ),
        migrations.AddField(
            model_name='durgasangha',
            name='category',
            field=models.CharField(default='দুর্গা সংঘ', help_text='যেমন: দুর্গা সংঘ, উপদেষ্টা, বিশেষ সদস্য', max_length=100, verbose_name='ক্যাটাগরি'),
        ),
        migrations.AddField(
            model_name='durgasangha',
            name='category_order',
            field=models.PositiveIntegerField(default=0, help_text='ছোট সংখ্যা আগে দেখাবে (যেমন: 1, 2, 3...)', verbose_name='ক্যাটাগরির ক্রম'),
        ),
        migrations.AlterField(
            model_name='durgasangha',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='একই ক্যাটাগরির মধ্যে সদস্যের ক্রম', verbose_name='সদস্যের ক্রম'),
        ),
    ]
