# Generated by Django 5.1.5 on 2025-11-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0018_alter_durgasangha_options_durgasangha_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='prasad_hall_image',
            field=models.ImageField(blank=True, help_text='হোম পেইজে প্রদর্শিত হবে', null=True, upload_to='settings/', verbose_name='প্রসাদ হল ও ভক্ত নিবাস ছবি'),
        ),
    ]
