# Generated by Django 5.1.5 on 2025-11-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durga', '0019_sitesettings_prasad_hall_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='ব্যাংকের নাম')),
                ('bank_account_name', models.CharField(blank=True, max_length=200, verbose_name='একাউন্ট নাম')),
                ('bank_account_number', models.CharField(blank=True, max_length=100, verbose_name='ব্যাংক একাউন্ট নাম্বার')),
                ('bank_branch', models.CharField(blank=True, max_length=200, verbose_name='ব্যাংক শাখা')),
                ('bank_routing_number', models.CharField(blank=True, max_length=50, verbose_name='রাউটিং নাম্বার')),
                ('bkash_number', models.CharField(blank=True, help_text='যেমন: ০১৭১১-১২৩৪৫৬', max_length=20, verbose_name='বিকাশ নাম্বার')),
                ('nagad_number', models.CharField(blank=True, help_text='যেমন: ০১৭১১-১২৩৪৫৬', max_length=20, verbose_name='নগদ নাম্বার')),
                ('rocket_number', models.CharField(blank=True, help_text='যেমন: ০১৭১১-১২৩৪৫৬', max_length=20, verbose_name='রকেট নাম্বার')),
                ('other_payment_info', models.TextField(blank=True, help_text='অন্য কোন পেমেন্ট পদ্ধতি থাকলে এখানে লিখুন', verbose_name='অন্যান্য পেমেন্ট তথ্য')),
                ('donation_note', models.TextField(blank=True, help_text='যেমন: দানের জন্য ধন্যবাদ বার্তা বা নির্দেশনা', verbose_name='দাতাদের জন্য বিশেষ বার্তা')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেটের তারিখ')),
            ],
            options={
                'verbose_name': 'দান/অনুদান তথ্য',
                'verbose_name_plural': 'দান/অনুদান তথ্য',
            },
        ),
    ]
